// <auto-generated />
namespace SDP_MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _10151914 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10151914));
        
        string IMigrationMetadata.Id
        {
            get { return "201510150814339_10151914"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
