// <auto-generated />
namespace SDP_MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _11021343 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11021343));
        
        string IMigrationMetadata.Id
        {
            get { return "201511020243483_11021343"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
