// <auto-generated />
namespace SDP_MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _10111055 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10111055));
        
        string IMigrationMetadata.Id
        {
            get { return "201510111158187_10111055"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
